# -*- coding: utf-8 -*-
"""Fraud Detection in Finance Transactions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awqXpwPBi8Uc8wEPx_xdLehKQTa4wNZW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

df = pd.read_csv('Fraud.csv')

print(df.head())

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nDuplicate rows count:", df.duplicated().sum())


df.fillna(0, inplace=True)

df['type'] = LabelEncoder().fit_transform(df['type'])
df['nameOrig'] = df['nameOrig'].apply(lambda x: 1 if x.startswith('C') else 0)  # Encoding customer vs merchant
df['nameDest'] = df['nameDest'].astype(str).apply(lambda x: 1 if x.startswith('C') else 0)

df['oldbalance_change'] = df['newbalanceOrig'] - df['oldbalanceOrg']
df['newbalance_change'] = df['newbalanceDest'] - df['oldbalanceDest']

plt.figure(figsize=(6, 4))
sns.countplot(x='isFraud', data=df)
plt.title("Fraud vs Non-Fraud Transactions")
plt.show()

plt.figure(figsize=(8, 6))
sns.countplot(x='type', data=df)
plt.title("Distribution of Transaction Types")
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df['amount'], bins=50, kde=True)
plt.title("Transaction Amount Distribution")
plt.show()

corr = df.corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()

X = df.drop(['isFraud', 'isFlaggedFraud'], axis=1)
y = df['isFraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

